### PR TITLE
Add edit delete

### PR DESCRIPTION
**Pull request by jimbandrews**
Add, edit, and delete snippet functionality has been implemented. HTML pages still need styling

### CODE REVIEW

**Comment by TrentHurlbut** [comment]
Looks like a couple of conflicts came up when Jeff's latest branch was merged into main. Do you want to resolve them yourself, or would you wanna do so as a group?

**Comment by jimbandrews** [comment]
I can take care of it once I get back from the drug store

**Comment by badmicro** [comment]
Yeah it looks good to me, I think you just need to merge the code and remove redundancies. I think that might only occur in views.py

**Comment by TrentHurlbut** [comment]
Lookin good! Very well commented.

**Pull request merged**
